/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ComprasPedidoView.java
 *
 * Created on 19/08/2012, 02:15:52
 */
package compra.pedido.view;

import compra.pedido.view.entidades.PedcabView;

/**
 *
 * @author leo
 */
public class ComprasPedidoView extends javax.swing.JFrame {

    /** Creates new form ComprasPedidoView */
    public ComprasPedidoView() {
        initComponents();
    }

    public PedcabView getPedcabView() {
        return pedcabView;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pedcabView = new compra.pedido.view.entidades.PedcabView();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pedcabView, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pedcabView, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ComprasPedidoView().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private compra.pedido.view.entidades.PedcabView pedcabView;
    // End of variables declaration//GEN-END:variables
}
