/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GradeView.java
 *
 * Created on 19/08/2012, 12:16:59
 */
package compra.pedido.view.entidades;

import javax.swing.JTextField;

/**
 *
 * @author leo
 */
public class GradeView extends javax.swing.JPanel {

    class AddCor extends JTextField {
    }
    
    class AddTamanho extends JTextField {
    }

    private GradeLayout gradeLayout = new GradeLayout();

    private AddCor addCor = new AddCor();
    private AddTamanho addTamanho = new AddTamanho();

    public AddCor getAddCor() {
        return addCor;
    }

    public AddTamanho getAddTamanho() {
        return addTamanho;
    }
    
    /** Creates new form GradeView */
    public GradeView() {
        initComponents();
        
        setLayout(gradeLayout);
        add(addCor);
        add(addTamanho);
        /*
        add(new PedgradtamView(1, 1, "1"));
        add(new PedgradtamView(2, 2, "2"));
        add(new PedgradtamView(3, 3, "3"));
        add(new PedgradtamView(4, 4, "4"));

        add(new PedgradcorView(1, 1, "1"));
        add(new PedgradcorView(2, 2, "2"));
        add(new PedgradcorView(3, 3, "3"));

        add(new PedgradqtdeView(1, 1));
        add(new PedgradqtdeView(2, 1));
        add(new PedgradqtdeView(3, 1));
        add(new PedgradqtdeView(4, 1));
        add(new PedgradqtdeView(1, 2));
        add(new PedgradqtdeView(2, 2));
        add(new PedgradqtdeView(3, 2));
        add(new PedgradqtdeView(4, 2));
        add(new PedgradqtdeView(1, 3));
        add(new PedgradqtdeView(2, 3));
        add(new PedgradqtdeView(3, 3));
        add(new PedgradqtdeView(4, 3));
         * 
         */
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
