/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ItemDoPedidoView.java
 *
 * Created on 11/08/2012, 14:19:17
 */
package jbean2.view;

import javax.swing.JButton;
import javax.swing.JTextField;
import jbean2.annotation.Action;
import jbean2.annotation.BindBean;
import jbean2.annotation.BindProperty;

/**
 *
 * @author leo
 */
@jbean2.annotation.View("ItemDoPedidoView")
public class ItemDoPedidoView extends javax.swing.JPanel {

    /** Creates new form ItemDoPedidoView */
    public ItemDoPedidoView() {
        initComponents();
    }

    @BindBean(
            property="ItemDoPedidoView.produtoView", 
            to="ItemDoPedido.produto")
    public ProdutoView getProdutoView() {
        return produtoView;
    }

    @BindProperty(
            property="ItemDoPedidoView.textQuantidade.text", 
            toAndfrom="ItemDoPedido.quantidade", 
            conversor="integerConversor")
    public JTextField getTextQuantidade() {
        return textQuantidade;
    }

    @Action(
            property="ItemDoPedidoView.buttonExcluir.action", 
            execute="sistemaDePedido.removerItem(ItemDoPedido.produto.codigo)", 
            label="Excluir", 
            update="view")
    public JButton getButtonExcluir() {
        return buttonExcluir;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textQuantidade = new javax.swing.JTextField();
        produtoView = new jbean2.view.ProdutoView();
        buttonExcluir = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Item do Pedido"));

        jLabel1.setText("Quantidade:");

        produtoView.setBorder(javax.swing.BorderFactory.createTitledBorder("Produto"));

        buttonExcluir.setText("Excluir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(produtoView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonExcluir)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(produtoView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonExcluir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonExcluir;
    private javax.swing.JLabel jLabel1;
    private jbean2.view.ProdutoView produtoView;
    private javax.swing.JTextField textQuantidade;
    // End of variables declaration//GEN-END:variables
}
