package jbean2.view;

import javax.swing.JButton;
import jbean2.annotation.Action;
import jbean2.annotation.BindBean;

/**
 *
 * @author leo
 */
@jbean2.annotation.View("View")
public class View extends javax.swing.JFrame {

    
    /** Creates new form View */
    public View() { 
        initComponents();
    }

    @Action(
            label="Abrir",
            execute="sistemaDePedido.abrirPedido(3345)",
            property="View.buttonAbrir.action",
            update="view")
    public JButton getButtonAbrir() {
        return buttonAbrir;
    }

    @Action(
            label="Adicionar Item", 
            execute="sistemaDePedido.adicionarItemNovo()", 
            property="View.buttonAdicionarItem.action", 
            update="view")
    public JButton getButtonAdicionarItem() {
        return buttonAdicionarItem;
    }

    @BindBean(property="View.pedidoView", to="SistemaDePedido.pedido")
    public PedidoView getPedidoView() {
        return pedidoView;
    }


    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonAdicionarItem = new javax.swing.JButton();
        pedidoView = new jbean2.view.PedidoView();
        textNumeroDoPedido = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        buttonAbrir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonAdicionarItem.setText("Adicionar item");

        jLabel1.setText("Numero do pedido:");

        buttonAbrir.setText("Abrir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textNumeroDoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAbrir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(buttonAdicionarItem)
                .addGap(74, 74, 74))
            .addComponent(pedidoView, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textNumeroDoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAdicionarItem)
                    .addComponent(buttonAbrir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pedidoView, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAbrir;
    private javax.swing.JButton buttonAdicionarItem;
    private javax.swing.JLabel jLabel1;
    private jbean2.view.PedidoView pedidoView;
    private javax.swing.JTextField textNumeroDoPedido;
    // End of variables declaration//GEN-END:variables
}
