/*
 * View.java
 *
 * Created on 30/12/2012, 20:52:43
 */
package teste2;

import java.util.ArrayList;
import java.util.Collection;
import javax.swing.JButton;

/**
 *
 * @author leo
 */
public class View extends javax.swing.JFrame {

    private Collection<TelefoneView> telefoneListView = new TelefoneListView();

    /** Creates new form View */
    public View() {


        initComponents();
    }

    private class TelefoneListView extends ArrayList<TelefoneView> {

        @Override
        public boolean add(TelefoneView e) {
            telefonesView.add(e);
            telefonesView.updateUI();
            repaint();
            return super.add(e);
        }

        @Override
        public boolean remove(Object o) {
            telefonesView.remove((TelefoneView) o);
            telefonesView.updateUI();
            repaint();
            return super.remove(o);
        }

        @Override
        public void clear() {
            telefonesView.removeAll();
            repaint();
            super.clear();
        }

        @Override
        public int hashCode() {
            return System.identityHashCode(TelefoneListView.this);
        }

        @Override
        public boolean equals(Object o) {
            return (this == o);
        }
    }

    public JButton getButtonUpdateModel() {
        return buttonUpdateModel;
    }

    public JButton getButtonUpdateView() {
        return buttonUpdateView;
    }

    public Collection<TelefoneView> getTelefoneListView() {
        return telefoneListView;
    }

    public JButton getButtonAdicionar() {
        return buttonAdicionar;
    }

    public JButton getButtonLimparTudo() {
        return buttonLimparTudo;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonUpdateModel = new javax.swing.JButton();
        buttonUpdateView = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        telefonesView = new javax.swing.JPanel();
        buttonAdicionar = new javax.swing.JButton();
        buttonLimparTudo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonUpdateModel.setText("Update model");

        buttonUpdateView.setText("Update model");

        jScrollPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        telefonesView.setBorder(null);
        telefonesView.setLayout(new javax.swing.BoxLayout(telefonesView, javax.swing.BoxLayout.PAGE_AXIS));
        jScrollPane2.setViewportView(telefonesView);

        buttonAdicionar.setText("Adicionar");

        buttonLimparTudo.setText("Limpar tudo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonLimparTudo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonUpdateModel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonUpdateView)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAdicionar)
                    .addComponent(buttonLimparTudo)
                    .addComponent(buttonUpdateModel)
                    .addComponent(buttonUpdateView))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdicionar;
    private javax.swing.JButton buttonLimparTudo;
    private javax.swing.JButton buttonUpdateModel;
    private javax.swing.JButton buttonUpdateView;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel telefonesView;
    // End of variables declaration//GEN-END:variables
}
