/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GradeView.java
 *
 * Created on 19/08/2012, 12:16:59
 */
package testegrade;

import compra.pedido.view.entidades.PedgradcorView;
import compra.pedido.view.entidades.PedgradqtdeView;
import compra.pedido.view.entidades.PedgradtamView;

/**
 *
 * @author leo
 */
public class GradeView extends javax.swing.JPanel {

    private GradeLayout gradeLayout = new GradeLayout();
    /** Creates new form GradeView */
    public GradeView() {
        initComponents();
        
        setLayout(gradeLayout);
        /*
        add(new PedgradtamView(1, 1, "1"));
        add(new PedgradtamView(2, 2, "2"));
        add(new PedgradtamView(3, 3, "3"));
        add(new PedgradtamView(4, 4, "4"));

        add(new PedgradcorView(1, 1, "1"));
        add(new PedgradcorView(2, 2, "2"));
        add(new PedgradcorView(3, 3, "3"));

        add(new PedgradqtdeView(1, 1));
        add(new PedgradqtdeView(2, 1));
        add(new PedgradqtdeView(3, 1));
        add(new PedgradqtdeView(4, 1));
        add(new PedgradqtdeView(1, 2));
        add(new PedgradqtdeView(2, 2));
        add(new PedgradqtdeView(3, 2));
        add(new PedgradqtdeView(4, 2));
        add(new PedgradqtdeView(1, 3));
        add(new PedgradqtdeView(2, 3));
        add(new PedgradqtdeView(3, 3));
        add(new PedgradqtdeView(4, 3));
         * 
         */
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
